FROM nginx:alpine
#COPY nginx-reverse.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf
#COPY reverse-proxy-upstream-conf.conf /etc/nginx/nginx.conf
#COPY public /usr/share/nginx/html

