FROM tomcat:8.0-jre8 

##RUN apt-get update && apt-get -y upgrade

WORKDIR /usr/local/tomcat

COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml
COPY server.xml /usr/local/tomcat/conf/server.xml

#Cppy the war file to tomcat/webapps
COPY User-Service.war /usr/local/tomcat/webapps/User-Service.war

##Request the port from Container OS
EXPOSE 9090