version: "3"
services:
  api-database:
    image: mongo
    container_name: "api-database"
    ports:
      - 27017:27017
    command: --smallfiles
  api:
    image: api-docker-app
    ports:
      - 9091:8080
    links:
      - api-database
